apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nflfrontend
        image: rakinkhan/nfl-frontend:kubernetes
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: apiserver
        image: rakinkhan/api-server:2024.12.25
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-cred

# kubectl apply -f deployment.yaml
# kubectl delete -f deployment.yaml