apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: server
  ports:
  - protocol: 'TCP'
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: myapp
  ports:
  - protocol: 'TCP'
    port: 3000
    targetPort: 80
  type: LoadBalancer