apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: server
  ports:
  - protocol: 'TCP'
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: myapp
  ports:
  - protocol: 'TCP'
    port: 3000
    targetPort: 80
  type: LoadBalancer

# kubectl apply -f service.yaml
# kubectl delete -f service.yaml

# minikube service frontend <-- command to expose frontend to browser
# minikube service backend <-- command to expose backend to browser